"""removing likes column on Posts and Comments

Revision ID: 7966ab4394c4
Revises: 54cb5b7fea98
Create Date: 2020-03-25 11:53:53.706286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7966ab4394c4'
down_revision = '54cb5b7fea98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'likes')
    op.drop_column('posts', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
